version: '3.7'
services:
  mariadb:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - ./installation/frappe-mariadb.cnf:/etc/mysql/conf.d/frappe.cnf
      - mariadb-data:/var/lib/mysql

  redis-cache:
    image: redis:alpine
    restart: always
    volumes:
      - redis-cache-data:/data

  redis-queue:
    image: redis:alpine
    restart: always
    volumes:
      - redis-queue-data:/data

  redis-socketio:
    image: redis:alpine
    restart: always
    volumes:
      - redis-socketio-data:/data

  backend:
    image: frappe/erpnext-worker:v14
    restart: always
    command: ["bench", "worker", "--queue", "default"]
    environment:
      - WORKER_TYPE=default
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites
    depends_on:
      - mariadb
      - redis-queue

  schedule:
    image: frappe/erpnext-worker:v14
    restart: always
    command: ["bench", "schedule"]
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites
    depends_on:
      - mariadb
      - redis-queue

  web:
    image: frappe/erpnext-worker:v14
    restart: always
    command: ["bench", "serve", "--port", "80"]
    environment:
      - FRAPPE_PY=gunicorn
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites
    ports:
      - "80:80"
    depends_on:
      - backend
      - redis-cache
      - redis-socketio

  socketio:
    image: frappe/frappe-socketio:v14
    restart: always
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites
    depends_on:
      - web
      - redis-socketio
    ports:
      - "9000:9000"

volumes:
  mariadb-data:
  redis-cache-data:
  redis-queue-data:
  redis-socketio-data:
  sites-vol:
