version: '3'

services:
  mariadb:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database_name
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_password
    volumes:
      - mariadb-data:/var/lib/mysql

  redis-cache:
    image: redis:alpine
    restart: always
    ports:
      - "6380:6379"

  redis-queue:
    image: redis:alpine
    restart: always
    ports:
      - "6381:6379"

  redis-socketio:
    image: redis:alpine
    restart: always
    ports:
      - "6382:6379"

  web:
    image: frappe/erpnext:v14
    restart: always
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio
    ports:
      - "8000:8000"
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites
      - assets-vol:/home/frappe/frappe-bench/sites/assets
    environment:
      DB_HOST: mariadb
      REDIS_CACHE: redis://redis-cache:6379
      REDIS_QUEUE: redis://redis-queue:6379
      REDIS_SOCKETIO: redis://redis-socketio:6379

  socketio:
    image: frappe/frappe-socketio:v14
    restart: always
    depends_on:
      - web
      - redis-socketio
    ports:
      - "9000:9000"
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites
    environment:
      REDIS_URL: redis://redis-socketio:6379

  backend:
    image: frappe/erpnext-worker:v14
    restart: always
    depends_on:
      - redis-queue
      - redis-cache
      - redis-socketio
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites
    environment:
      DB_HOST: mariadb
      REDIS_CACHE: redis://redis-cache:6379
      REDIS_QUEUE: redis://redis-queue:6379
      REDIS_SOCKETIO: redis://redis-socketio:6379

  webserver:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - sites-vol:/usr/share/nginx/html

volumes:
  mariadb-data:
  sites-vol:
  assets-vol:
