version: '3.7'
services:
  mariadb:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis-cache:
    image: redis:alpine
    restart: always
    volumes:
      - redis-cache-data:/data

  redis-queue:
    image: redis:alpine
    restart: always
    volumes:
      - redis-queue-data:/data

  redis-socketio:
    image: redis:alpine
    restart: always
    volumes:
      - redis-socketio-data:/data

  backend:
    image: frappe/erpnext-worker:v14
    restart: always
    command: worker
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites
    depends_on:
      - mariadb
      - redis-queue

  schedule:
    image: frappe/erpnext-worker:v14
    restart: always
    command: schedule
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites
    depends_on:
      - mariadb
      - redis-queue

  web:
    image: frappe/erpnext-worker:v14
    restart: always
    command: serve
    ports:
      - "80:8000"
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites
    depends_on:
      - backend
      - redis-cache
      - redis-socketio

  socketio:
    image: frappe/frappe-socketio:v14
    restart: always
    depends_on:
      - web
      - redis-socketio
    ports:
      - "9000:9000"
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites

volumes:
  mariadb-data:
  redis-cache-data:
  redis-queue-data:
  redis-socketio-data:
  sites-vol:
